### ISSUE TITLE
Deprecate Some Features

### ISSUE THREAD

**Issue by HeteroChromia42** [alexavil/DoppelBot#15]
I decided to open this issue after our talk in the DMs, i feel it might be time to deprecate some of the features that Doppelbot has, since i feel that DoppelBot's main focus has become the music feature, so, here's a formalization of the Proposal:

Deprecate the following features (due to not being used often):
d!doppel, and other stuff related to it, as well as the daily doppel stuff and party stuff.

**Comment by alexavil** [comment]
Most of features are deprecated on the `q` branch.
